name: C++ Format and PR
on:
  schedule:
    # Run every hour to check for changes
    - cron: '0 * * * *'
  workflow_dispatch:
  # Allow manual triggering
jobs:
  format-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/UB-CSE/LED-Video-Wall.git
          git fetch upstream
      - name: Check for changes in upstream
        id: check-changes
        run: |
          git merge-base --is-ancestor HEAD upstream/main || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Sync with upstream
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git pull upstream main
      - name: Setup C++ Tools
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Format C++ code
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -i -style=file
      - name: Create branch and commit changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git checkout -b auto-format-$(date +%Y%m%d%H%M%S)
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-format C++ code"
      - name: Push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git push origin HEAD
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Apply C++ formatting
          title: Automated C++ formatting
          body: |
            This PR automatically formats C++ code according to the project's style guide.

            Generated by GitHub Actions.
          branch: auto-format
          base: main
